CREATE TABLE IF NOT EXISTS `tsm_oo_report_view` (
  `VIEWID` varchar(8) NOT NULL COMMENT 'YYYYMMDD',
  `OPEARTORLIST` varchar(512)  DEFAULT NULL COMMENT '运营机构列表，#号隔开',
  `LOADSUCCESS_D` varchar(128) DEFAULT NULL COMMENT '加载成功数(按天)',
  `LOADERROR_D` varchar(128) DEFAULT NULL COMMENT '加载失败数(按天)',
  `DELSUCCESS_D` varchar(128) DEFAULT NULL COMMENT '删除成功数(按天)',
  `DELERROR_D` varchar(128) DEFAULT NULL COMMENT '删除失败数(按天)',
  `LOCKSUCCESS_D` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按天)',
  `LOCKERROR_D` varchar(128) DEFAULT  NULL COMMENT '锁定失败数(按天)',
  `UNLOCKSUCCESS_D` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按天)',
  `UNLOCKERROR_D` varchar(128) DEFAULT NULL COMMENT '锁定失败数(按天)',
  `LOADSUCCESS_W` varchar(128) DEFAULT NULL COMMENT '加载成功数(按周)',
  `LOADERROR_W` varchar(128) DEFAULT NULL COMMENT '加载失败数(按周)',
  `DELSUCCESS_W` varchar(128) DEFAULT NULL COMMENT '删除成功数(按周)',
  `DELERROR_W` varchar(128) DEFAULT NULL COMMENT '删除失败数(按周)',
  `LOCKSUCCESS_W` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按周)',
  `LOCKERROR_W` varchar(128) DEFAULT  NULL COMMENT '锁定失败数(按周)',
  `UNLOCKSUCCESS_W` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按周)',
  `UNLOCKERROR_W` varchar(128) DEFAULT NULL COMMENT '锁定失败数(按周)',
  `LOADSUCCESS_M` varchar(128) DEFAULT NULL COMMENT '加载成功数(按月)',
  `LOADERROR_M` varchar(128) DEFAULT NULL COMMENT '加载失败数(按月)',
  `DELSUCCESS_M` varchar(128) DEFAULT NULL COMMENT '删除成功数(按月)',
  `DELERROR_M` varchar(128) DEFAULT NULL COMMENT '删除失败数(按月)',
  `LOCKSUCCESS_M` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按月)',
  `LOCKERROR_M` varchar(128) DEFAULT  NULL COMMENT '锁定失败数(按月)',
  `UNLOCKSUCCESS_M` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按月)',
  `UNLOCKERROR_M` varchar(128) DEFAULT NULL COMMENT '锁定失败数(按月)',
  `IP` varchar(64) DEFAULT  NULL COMMENT '执行IP',
  `HOSTNAME` varchar(64) DEFAULT NULL COMMENT '机器名',
  `BEGINTIME` datetime DEFAULT NULL COMMENT '统计开始时间',
  `ENDTIME` datetime DEFAULT NULL COMMENT '统计结束时间',
  `STATUS` char(1)  DEFAULT NULL COMMENT '统计状态0-统计完成 1-统计失败 2-统计中',
  `ERRORMSG` varchar(200) DEFAULT NULL COMMENT '错误信息',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
   PRIMARY KEY (`VIEWID`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='机构统计报表视图表';

CREATE TABLE IF NOT EXISTS `tsm_mf_report_view` (
  `VIEWID` varchar(8) NOT NULL COMMENT 'YYYYMMDD',
  `OPEARTORLIST` varchar(512)  DEFAULT NULL COMMENT '运营机构列表，#号隔开',
  `LOADSUCCESS_D` varchar(128) DEFAULT NULL COMMENT '加载成功数(按天)',
  `LOADERROR_D` varchar(128) DEFAULT NULL COMMENT '加载失败数(按天)',
  `DELSUCCESS_D` varchar(128) DEFAULT NULL COMMENT '删除成功数(按天)',
  `DELERROR_D` varchar(128) DEFAULT NULL COMMENT '删除失败数(按天)',
  `LOCKSUCCESS_D` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按天)',
  `LOCKERROR_D` varchar(128) DEFAULT  NULL COMMENT '锁定失败数(按天)',
  `UNLOCKSUCCESS_D` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按天)',
  `UNLOCKERROR_D` varchar(128) DEFAULT NULL COMMENT '锁定失败数(按天)',
  `LOADSUCCESS_W` varchar(128) DEFAULT NULL COMMENT '加载成功数(按周)',
  `LOADERROR_W` varchar(128) DEFAULT NULL COMMENT '加载失败数(按周)',
  `DELSUCCESS_W` varchar(128) DEFAULT NULL COMMENT '删除成功数(按周)',
  `DELERROR_W` varchar(128) DEFAULT NULL COMMENT '删除失败数(按周)',
  `LOCKSUCCESS_W` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按周)',
  `LOCKERROR_W` varchar(128) DEFAULT  NULL COMMENT '锁定失败数(按周)',
  `UNLOCKSUCCESS_W` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按周)',
  `UNLOCKERROR_W` varchar(128) DEFAULT NULL COMMENT '锁定失败数(按周)',
  `LOADSUCCESS_M` varchar(128) DEFAULT NULL COMMENT '加载成功数(按月)',
  `LOADERROR_M` varchar(128) DEFAULT NULL COMMENT '加载失败数(按月)',
  `DELSUCCESS_M` varchar(128) DEFAULT NULL COMMENT '删除成功数(按月)',
  `DELERROR_M` varchar(128) DEFAULT NULL COMMENT '删除失败数(按月)',
  `LOCKSUCCESS_M` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按月)',
  `LOCKERROR_M` varchar(128) DEFAULT  NULL COMMENT '锁定失败数(按月)',
  `UNLOCKSUCCESS_M` varchar(128) DEFAULT NULL COMMENT '锁定成功数(按月)',
  `UNLOCKERROR_M` varchar(128) DEFAULT NULL COMMENT '锁定失败数(按月)',
  `IP` varchar(64) DEFAULT  NULL COMMENT '执行IP',
  `HOSTNAME` varchar(64) DEFAULT NULL COMMENT '机器名',
  `BEGINTIME` datetime DEFAULT NULL COMMENT '统计开始时间',
  `ENDTIME` datetime DEFAULT NULL COMMENT '统计结束时间',
  `STATUS` char(1)  DEFAULT NULL COMMENT '统计状态0-统计完成 1-统计失败 2-统计中',
  `ERRORMSG` varchar(200) DEFAULT NULL COMMENT '错误信息',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
   PRIMARY KEY (`VIEWID`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='厂商统计报表视图表';

CREATE TABLE IF NOT EXISTS `tsm_tx_report_view` (
  `VIEWID` varchar(8) NOT NULL COMMENT 'YYYYMMDD',
  `TXCODELIST` varchar(512)  DEFAULT NULL COMMENT '交易码列表 640#641#642',
  `TXCODE_SUCCESS_D` varchar(128) DEFAULT NULL COMMENT '用交易码统计成功数(按天)',
  `TXCODE_ERROR_D` varchar(128) DEFAULT NULL COMMENT '用交易码统计失败数(按天)',
  `TXCODE_SUCCESS_W` varchar(128) DEFAULT NULL COMMENT '用交易码统计成功数(按周)',
  `TXCODE_ERROR_W` varchar(128) DEFAULT NULL COMMENT '用交易码统计失败数(按周)',
  `TXCODE_SUCCESS_M` varchar(128) DEFAULT NULL COMMENT '用交易码统计成功数(按月)',
  `TXCODE_ERROR_M` varchar(128) DEFAULT NULL COMMENT '用交易码统计失败数(按月)',
  `OPEARTORLIST` varchar(512)  DEFAULT NULL COMMENT '运营机构列表，#号隔开',
  `OPEARTOR_SUCCESS_D` varchar(128) DEFAULT NULL COMMENT '用运营机构统计成功数(按天)',
  `OPEARTOR_ERROR_D` varchar(128) DEFAULT NULL COMMENT '用运营机构统计失败数(按天)',
  `OPEARTOR_SUCCESS_W` varchar(128) DEFAULT NULL COMMENT '用运营机构统计成功数(按周)',
  `OPEARTOR_ERROR_W` varchar(128) DEFAULT NULL COMMENT '用运营机构统计失败数(按周)',
  `OPEARTOR_SUCCESS_M` varchar(128) DEFAULT NULL COMMENT '用运营机构统计成功数(按月)',
  `OPEARTOR_ERROR_M` varchar(128) DEFAULT NULL COMMENT '用运营机构统计失败数(按月)',
  `SUCCESS_D` varchar(128) DEFAULT NULL COMMENT '用交易状态统计成功数(按天)',
  `ERROR_D` varchar(128) DEFAULT NULL COMMENT '用交易状态统计失败数(按天)',
  `SUCCESS_W` varchar(128) DEFAULT NULL COMMENT '用交易状态统计成功数(按周)',
  `ERROR_W` varchar(128) DEFAULT NULL COMMENT '用交易状态统计失败数(按周)',
  `SUCCESS_M` varchar(128) DEFAULT NULL COMMENT '用交易状态统计成功数(按月)',
  `ERROR_M` varchar(128) DEFAULT NULL COMMENT '用交易状态统计失败数(按月)',
  `TOTAl` varchar(64) DEFAULT  NULL COMMENT '交易总数',
  `IP` varchar(64) DEFAULT  NULL COMMENT '执行IP',
  `HOSTNAME` varchar(64) DEFAULT NULL COMMENT '机器名',
  `BEGINTIME` datetime DEFAULT NULL COMMENT '统计开始时间',
  `ENDTIME` datetime DEFAULT NULL COMMENT '统计结束时间',
  `STATUS` char(1)  DEFAULT NULL COMMENT '统计状态0-统计完成 1-统计失败 2-统计中',
  `ERRORMSG` varchar(200) DEFAULT NULL COMMENT '错误信息',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
   PRIMARY KEY (`VIEWID`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='交易统计报表视图表';

CREATE TABLE IF NOT EXISTS `tsm_mt_report_view` (
  `VIEWID` varchar(8) NOT NULL COMMENT 'YYYYMMDD',
  `MEDIUMTYPELIST` varchar(512)  DEFAULT NULL COMMENT '介质类型列表，#号隔开',
  `TOTAL_D` varchar(128) DEFAULT NULL COMMENT '加载完成数(按天)#号隔开',
  `TOTAL_W` varchar(128) DEFAULT NULL COMMENT '加载完成数(按周)#号隔开',
  `TOTAL_M` varchar(128) DEFAULT NULL COMMENT '加载完成数(按月)#号隔开',
  `IP` varchar(64) DEFAULT  NULL COMMENT '执行IP',
  `HOSTNAME` varchar(64) DEFAULT NULL COMMENT '机器名',
  `BEGINTIME` datetime DEFAULT NULL COMMENT '统计开始时间',
  `ENDTIME` datetime DEFAULT NULL COMMENT '统计结束时间',
  `STATUS` char(1)  DEFAULT NULL COMMENT '统计状态0-统计完成 1-统计失败 2-统计中',
  `ERRORMSG` varchar(200) DEFAULT NULL COMMENT '错误信息',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
   PRIMARY KEY (`VIEWID`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='介质类型统计报表视图表';

CREATE TABLE IF NOT EXISTS `tsm_err_report_view` (
  `VIEWID` varchar(8) NOT NULL COMMENT 'YYYYMMDD',
  `ERRORLIST` varchar(512)  DEFAULT NULL COMMENT '错误码列表，#号隔开',
  `ERRORMSGLIST` varchar(2048)  DEFAULT NULL COMMENT '错误信息列表，#号隔开',
  `TOTAL_D` varchar(128) DEFAULT NULL COMMENT '统计数(按天)#号隔开',
  `TOTAL_W` varchar(128) DEFAULT NULL COMMENT '统计数(按周)#号隔开',
  `TOTAL_M` varchar(128) DEFAULT NULL COMMENT '统计数(按月)#号隔开',
  `IP` varchar(64) DEFAULT  NULL COMMENT '执行IP',
  `HOSTNAME` varchar(64) DEFAULT NULL COMMENT '机器名',
  `BEGINTIME` datetime DEFAULT NULL COMMENT '统计开始时间',
  `ENDTIME` datetime DEFAULT NULL COMMENT '统计结束时间',
  `STATUS` char(1)  DEFAULT NULL COMMENT '统计状态0-统计完成 1-统计失败 2-统计中',
  `ERRORMSG` varchar(200) DEFAULT NULL COMMENT '错误信息',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
   PRIMARY KEY (`VIEWID`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='错误信息统计报表视图表';

CREATE TABLE IF NOT EXISTS `tsm_tr_report_view` (
  `VIEWID` varchar(8) NOT NULL COMMENT 'YYYYMMDD',
  `TOTAL_D` varchar(128) DEFAULT NULL COMMENT '加载完成数(按天)',
  `TOTAL_W` varchar(128) DEFAULT NULL COMMENT '加载完成数(按周)',
  `TOTAL_M` varchar(128) DEFAULT NULL COMMENT '加载完成数(按月)',
  `IP` varchar(64) DEFAULT  NULL COMMENT '执行IP',
  `HOSTNAME` varchar(64) DEFAULT NULL COMMENT '机器名',
  `BEGINTIME` datetime DEFAULT NULL COMMENT '统计开始时间',
  `ENDTIME` datetime DEFAULT NULL COMMENT '统计结束时间',
  `STATUS` char(1)  DEFAULT NULL COMMENT '统计状态0-统计完成 1-统计失败 2-统计中',
  `ERRORMSG` varchar(200) DEFAULT NULL COMMENT '错误信息',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
   PRIMARY KEY (`VIEWID`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='留存总数统计报表视图表';
