# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        #driverClassName: com.ydxsafe.dedb.driver.ShardingSphereDriver
        #driverCLassName: com.ciphergateway.aoe.plugin.engine.AOEDriver
        druid:
            # 主库数据源
            master:
                #url: jdbc:mysql://10.11.6.153:3306/edbtest1?serverTimezone=UTC&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&useServerPrepStmts=false&rewriteBatchedStatements=true
                #url: jdbc:shardingsphere:classpath:sharding.yaml
                url: jdbc:mysql://47.115.53.79:3306/test2?serverTimezone=UTC&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&useServerPrepStmts=false&rewriteBatchedStatements=true
                username: jiangyw
                password: JIANGYuwen1868
                #url: jdbc:mysql://localhost:3306/test2?serverTimezone=UTC&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
                #username: root
                #password: 123456
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: jdbc:mysql://47.115.53.79:3306/edbtest?serverTimezone=UTC&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&useServerPrepStmts=false&rewriteBatchedStatements=true
                username: edbtest
                password: edbtest@123
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 5
            # 最大连接池数量
            maxActive: 100
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: 
                login-password: 
#            filter:
#                stat:
#                    enabled: true
#                    # 慢SQL记录
#                    log-slow-sql: true
#                    slow-sql-millis: 1000
#                    merge-sql: true
#                wall:
#                    config:
#                        multi-statement-allow: true
