#ID
SDK_ID=1991793521197129729
#CASB: server protocol (http/https)
PROTOCOL=https
#CASB: server host
HOST=10.11.6.153
#CASB: server port
PORT=8443
#CASB: server url prefix
URL_PREFIX=
#CASB: Token Authentication enabled
TOKEN_ENABLED=1
#CASB: user name
USER_NAME=1991793521197129729
#CASB: user password
USER_SECRET=+OG06W+aSvFZl1FU8BylA/KJtn8f+zuacVHRlGRghOdEcD98uOTJdGP00q7ie6ve
#CASB: certificate name
CERTIFICATE_NAME=1763715556185_3fb3b281d4e532e98282d460fc0e9bc7.p12
#CASB: certificate password
CERTIFICATE_SECRET=2YC8cUnxIt+AAzvf62LbIAIC5CR3FzEtrBSEuCgWVpzDY9VU1fGOjmk1ZK0yxcnV
#SDK: Key cache state(on/off)
CACHE_SWITCH=on
#SDK: Key cache number
CACHE_KEY_NUM=1000
#SDK: Number of times the key is used. Update the key after the number of times is exceeded
ENCRYPT_KEY_COUNT=0
#SDK: Encryption key usage time (unit: second). Update the key when the time exceeds
ENCRYPT_KEY_EXPIRE=0
#SDK: Decryption key usage time (unit: second). Update the key when the time exceeds
DECRYPT_KEY_EXPIRE=0
#SDK: work mode(0-aux,1-process)
WORK_MODE=0
#SDK: kms rest path
KMS_REST_PATH=/kms/v1/sdk
#SDK: kms retry num
KMS_RETRY_NUM=3
#SDK: Log level (0- Sys logs/ 1-ERROR / 2-INFO)
CS_LOG_FLAG=1
#SDK:  Log path (generated from the install shell file)
LOG_PATH=D:\\CipherSuiteSdk_windows
#SDK:  home directory (generated from the install shell file)
SDK_BASE_PATH=D:\\CipherSuiteSdk_windows
#Plugin: Plugin type (aoe/proxy)
PLUGIN_TYPE=aoe
#Plugin: DB driver name list
DRIVER_LIST=com.mysql.cj.jdbc.Driver,oracle.jdbc.OracleDriver,org.postgresql.Driver,com.microsoft.sqlserver.jdbc.SQLServerDriver,dm.jdbc.driver.DmDriver,com.kingbase8.Driver,com.gbase.jdbc.Driver,com.vertica.jdbc.Driver,org.mariadb.jdbc.Driver,com.teradata.jdbc.TeraDriver,com.alipay.oceanbase.jdbc.Driver,com.ibm.db2.jcc.DB2Driver,com.oscar.Driver,ru.yandex.clickhouse.ClickHouseDriver,com.huawei.gauss.jdbc.ZenithDriver,com.tmax.tibero.jdbc.TbDriver
#Plugin: aoe strategy polling period (Unit s)
STRATEGY_PERIOD=180
#AOE exception handling method, 0-no exception is thrown externally, 1-exception is thrown externally
AOE_EXCEPTION_LEVEL=0
#desensitization (0/1)
AOE_DATAMASK=1
#User level (0/1)
APP_USER_LEVEL_OPEN=0
