logging:
  level:
    com.anydef.csp: debug
server:
  port: 8201
  servlet: 
    context-path: '/cspGateway'
  tomcat:
   max-connections: 10000
   accept-count: 3000
   max-threads: 400
   min-spare-threads: 3

jasypt:
  encryptor:
    password: anydef@csp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jyw.csp.entity
  configuration:
    database-id: mysql
    default-fetch-size: 500
    default-statement-timeout: 80

spring:
  mvc.view.prefix: /WEB-INF/jsp
  mvc.view.suffix: .jsp
  mvc.async.request-timeout: 20000
  datasource:
#    type: com.dcep.tsm.config.CustomizeDruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: oracle.jdbc.OracleDriver
    username: jiangyw
    password: JIANGYuwen1868
#    url: jdbc:oracle:thin:@localhost:1521:orcl
    url: jdbc:mysql://47.115.53.79:3306/test2?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
#    urls: jdbc:mysql://127.0.0.1:3306/dceptsm?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8, jdbc:mysql://127.0.0.1:3306/dceptsm?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    druid:
      filters: stat
      max-active: 100
      initial-size: 10
      min-idle: 10
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      max-wait: 3000
      time-between-eviction-runs-millis: 60000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
      statViewServlet:
          enabled: true  # 设置白名单，不填则允许所有访问
          allow:
          url-pattern: /druid/* # 控制台管理用户名和密码
          login-username:
          login-password:
  data:
    redis:
      host: 10.11.6.152
      port: 6379
      password: "123456"
      database: 0
      timeout: 2000ms

      sentinel:
        enabled: false
        nodes: 10.11.6.152:26379,10.11.6.153:26379,10.11.6.154:26379
        master: mymaster      

      lettuce:
        pool:
          max-active: 300
          max-idle: 80
          min-idle: 20
          max-wait: 3000ms
        client:
          share-native-connection: false

  #配置rabbitMq 服务器
  rabbitmq:
    addresses: 192.168.30.2:22032,192.168.30.2:22039,192.168.30.2:22046 #指定client连接到的server的地址，多个以逗号分隔(优先取addresses，然后再取host)
    username: admin
    password: 123
    virtual-host: /
redis:
 key:
  expire: 1800000
 passwd: admin123
 
# Resilience4j配置
resilience4j:
  circuitbreaker:
    instances:
      accessCircuitBreaker:
        failureRateThreshold: 50
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  ratelimiter:
    instances:
      accessRateLimiter:
        limitForPeriod: 1   # 每个周期只能通过 1 个请求
        limitRefreshPeriod: 1s # 周期长度 1 秒
        timeoutDuration: 0s # 许可等待超时时间 0 - 不排队，立即失败
      accessUserRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
      accessIpRateLimiter:
        limitForPeriod: 20
        limitRefreshPeriod: 1s
  timelimiter:
    instances:
      accessTimeLimiter:
        timeoutDuration: 3s
