# 租户编号
client.tenantId=dm
# 应用编号
client.appId=dm
# 应用密钥
client.appScrect=FCED0F045A435E35F9B97D117C8C609A

# 连接不同的 server，多个 server 以分号（;）隔开
client.serverAddress=10.193.60.36:8088
# 服务路径
client.serverPath=/cspGateway/mainAccess

# writeTimeout HTTP 通讯写入超时时间（单位：毫秒）
client.writeTimeout=300000
# readTimeout HTTP 通讯读取超时时间（单位：毫秒）
client.readTimeout=300000

# 是否启用安全认证，默认 true
client.secAuth=true

# 是否使用代理访问（true/false）
client.isUsedProxy=false
# 代理服务器IP地址
client.proxy_ip=
# 代理服务器端口
client.proxy_prot=80

# 是否启用 HTTPS（true/false）
client.enableHttps=false
# 客户端证书类型
client.storeType=PKCS12
# 客户端证书
client.clientCert=cert/sm2.pfx
# 客户端证书密码
client.clientCertPwd=12345678
# 信任证书库
client.trustCert=cert/demo1.sm2.trust.pem
# SSL协议
client.sslProtocol=GMSSLv1.1
# 支持的协议
client.supportedProtocols=GMSSLv1.1
# 支持的加密套件
client.supportedCipherSuites=ECC_SM4_GCM_SM3,ECC_SM4_CBC_SM3,ECDHE_SM4_GCM_SM3,ECDHE_SM4_CBC_SM3
